ansys/pymechanical

- README.rst
> DOCS: Removing caution message

- .github/workflows/ci_cd.yml
change runner from public-ubuntu-latest-16-cores to public-ubuntu-latest-8-cores.
> change runner

- docker/232/.dockerignore
cleanup the docker ignore file.
> cleanup docker ignore file

- .github/workflows/ci_cd.yml
- doc/source/getting_started/running_mechanical.rst
Fixes the typos in the documentation for launching standalone mechanical
https://github.com/pyansys/pymechanical/issues/212
> Fixes the windows executable path for standalone mechanical

- .github/workflows/ci_cd.yml
Solving issues in #214 - we decided to do a new release of our actions including this
> FIX: not necessary anymore to update apt-get

- CHANGELOG.md
- src/ansys/mechanical/core/embedding/app.py
new() in BUILDING_GALLERY constructor
re-add close()
fixes #223 
fixes #204
> updates to app

- .gitignore
ignore generated  *.ipynb, *.py, *.rst, *.md5, *.png and *.pickle files
> ignore generated  *.ipynb, *.py, *.rst, *.md5, *.png and *.pickle files

- .github/workflows/ci_cd.yml
- .github/workflows/label.yml
- CHANGELOG.md
- README.rst
- doc/source/conf.py
- doc/source/contributing.rst
- doc/source/getting_started/docker.rst
- doc/source/getting_started/faq.rst
- doc/source/getting_started/index.rst
- doc/source/getting_started/wsl.rst
- doc/source/links.rst
- docker/docker-compose.license_server.yml
- docker/docker-compose.yml
- docker/make_container.rst
- pyproject.toml
- src/ansys/mechanical/core/examples/downloads.py
As title says. Coming from org rename
> FIX: GitHub organization rename to Ansys

- doc/source/examples/index.rst
- doc/source/examples/pymechanical_examples_repo/index.rst
- doc/source/links.rst
link remote sessions samples from https://examples.mechanical.docs.pyansys.com/
> link to pymechanical remote sessions examples

- doc/source/examples/pymechanical_examples_repo/index.rst
> fix examples links

- doc/source/user_guide_embedding/logging.rst
Added "import logging" to fix failing code block in documentation. Closes #298
> added import logging to doc file

- doc/source/getting_started/running_mechanical.rst
Changed "in order to" -> "to" and put double backticks around launch
> Update wording in running_mechanical.rst

- CHANGELOG.md
- doc/source/conf.py
- doc/source/getting_started/docker.rst
- doc/source/getting_started/faq.rst
- doc/source/getting_started/wsl.rst
> fix: broken links

- CHANGELOG.md
- src/ansys/mechanical/core/run.py
Only show warning message for input script if revision is < 241.
> Added version check for ansys-mechanical warning message

- .github/workflows/ci_cd.yml
- CHANGELOG.md
Added changelog check to CI/CD yaml file to run for pull requests. Closes #272
> Add changelog check to CI/CD 

- CHANGELOG.md
- doc/source/user_guide_embedding/configuration.rst
- doc/source/user_guide_embedding/index.rst
- pyproject.toml
- src/ansys/mechanical/core/embedding/__init__.py
- src/ansys/mechanical/core/embedding/addins.py
- src/ansys/mechanical/core/embedding/app.py
- src/ansys/mechanical/core/embedding/config.py
- tests/conftest.py
- tests/embedding/test_logger.py
- tests/scripts/embedding_log_test.py
Add the addin configuration and unit tests.
Need to find a way to restrict unit test to version 241
> addin configuration and tests

- CHANGELOG.md
- doc/source/getting_started/running_mechanical.rst
- src/ansys/mechanical/core/embedding/app.py
- src/ansys/mechanical/core/embedding/appdata.py
- src/ansys/mechanical/core/embedding/initializer.py
- src/ansys/mechanical/core/run.py
Allow the following new flags:
`--private-appdata`
`--exit`
> New features for `ansys-mechanical` console script

- .github/workflows/ci_cd.yml
- CHANGELOG.md
> cicd: follow up of dependabot automated changelog

- .pre-commit-config.yaml
- .reuse/dep5
- .reuse/templates/ansys.jinja2
- CHANGELOG.md
- src/ansys/mechanical/core/__init__.py
- src/ansys/mechanical/core/_version.py
- src/ansys/mechanical/core/embedding/__init__.py
- src/ansys/mechanical/core/embedding/addins.py
- src/ansys/mechanical/core/embedding/app.py
- src/ansys/mechanical/core/embedding/appdata.py
- src/ansys/mechanical/core/embedding/imports.py
- src/ansys/mechanical/core/embedding/initializer.py
- src/ansys/mechanical/core/embedding/loader.py
- src/ansys/mechanical/core/embedding/logger/__init__.py
- src/ansys/mechanical/core/embedding/logger/environ.py
- src/ansys/mechanical/core/embedding/logger/linux_api.py
- src/ansys/mechanical/core/embedding/logger/sinks.py
- src/ansys/mechanical/core/embedding/logger/windows_api.py
- src/ansys/mechanical/core/embedding/resolver.py
- src/ansys/mechanical/core/embedding/runtime.py
- src/ansys/mechanical/core/embedding/shims.py
- src/ansys/mechanical/core/errors.py
- src/ansys/mechanical/core/examples/__init__.py
- src/ansys/mechanical/core/examples/downloads.py
- src/ansys/mechanical/core/launcher.py
- src/ansys/mechanical/core/logging.py
- src/ansys/mechanical/core/mechanical.py
- src/ansys/mechanical/core/misc.py
- src/ansys/mechanical/core/pool.py
- src/ansys/mechanical/core/run.py
Added .reuse directory
Added ansys-pre-commit-hooks to pyproject.toml
Added license headers to all files in the src directory
> Add license headers to files in src

- .github/workflows/ci_cd.yml
- CHANGELOG.md
- doc/source/user_guide_embedding/globals.rst
- src/ansys/mechanical/core/embedding/enum_importer.py
- src/ansys/mechanical/core/embedding/imports.py
- tests/embedding/test_qk_eng_wb2.py
> add option to include enums in global variables

- .github/workflows/ci_cd.yml
- CHANGELOG.md
- src/ansys/mechanical/core/embedding/app.py
- tests/embedding/test_app.py
> Fix stale globals by wrapping them

- CHANGELOG.md
- doc/source/user_guide_embedding/index.rst
- doc/source/user_guide_embedding/libraries.rst
- src/ansys/mechanical/core/embedding/app_libraries.py
> add experimental libraries method

- CHANGELOG.md
- src/ansys/mechanical/core/embedding/utils.py
- tests/embedding/test_app.py
Fixes #263 
This could also be used for remote session - but I'm not sure how best to import the util file in that case (or if we should do something different there, since util might eventually contain things that aren't usable in the remote interface)
> add nonblocking sleep

- CHANGELOG.md
- src/ansys/mechanical/core/mechanical.py
> minor doc correction

- CHANGELOG.md
- pyproject.toml
> Fix enum printout

- .github/workflows/codeql.yml
- CHANGELOG.md
> Add codeql.yml for security checks

- .github/workflows/ci_cd.yml
- CHANGELOG.md
- tests/scripts/run_embedded_app.py
The version number needs to be an int, not a string. This fixes the tests on windows when I run locally
> fix appdata tests

- CHANGELOG.md
- tests/embedding/test_logger.py
- tests/scripts/embedding_log_test.py
this is no longer supported in 241
> remove legacy configuration test

- CHANGELOG.md
- src/ansys/mechanical/core/embedding/app.py
- tests/conftest.py
> add readonly flag and assertion

- .github/workflows/ci_cd.yml
- CHANGELOG.md
Add doc pdf build step to the documentation section of the workflow. This is necessary for the release to work
> Add doc pdf build to workflow

- CHANGELOG.md
- src/ansys/mechanical/core/run.py
Finding version number is redundant and removing
> Fix cli find mechanical

- CHANGELOG.md
Create new "unreleased" section after 0.10.6 release
> Update changelog for 0.10.6 release

- .github/workflows/ci_cd.yml
- CHANGELOG.md
- pyproject.toml
- Update the dependency package version
- Update setup python in workflow
> MAINT: Bump ```ansys.mechanical.env``` from 0.1.2 to 0.1.3

- CHANGELOG.md
- src/ansys/mechanical/core/embedding/imports.py
- tests/embedding/test_globals.py
Adding mechanicalEnums to global
> Fix: Add MechanicalEnums 

- .github/workflows/ci_cd.yml
- CHANGELOG.md
Scheduled run :  242
PR : 241
Release : Use all stable versions (231,232,241)
> Fix : Update Release action to use Stable version of Mechanical

- .github/workflows/ci_cd.yml
- CHANGELOG.md
Update time out for doc build action 
Update runner for embedding
> Maint: update timeout for actions

- .github/workflows/ci_cd.yml
- CHANGELOG.md
Updating changelog after release of 10.8
fixes pdf generation action
> Fix: Make pdf action in doc build

- CHANGELOG.md
- doc/source/user_guide_embedding/index.rst
- doc/styles/config/vocabularies/ANSYS/accept.txt
Add usage of `ansys-mechanical` cli for executing a python script
Closes #346
> Doc: Add usage of cli under embedding

- .github/CODEOWNERS
- .github/dependabot.yml
- .github/labeler.yml
- doc/changelog.d/666.added.md
- Groups dependabot alerts
-  Add code owners file
-  Modify labeler
> FEAT: Group dependabot alerts

- .github/workflows/dependabot_automerge.yml
- doc/changelog.d/674.changed.md
Automating approval and merge of dependabot PR. Ref : https://github.com/ansys/pyansys-geometry/pull/956
> Maint: Auto approve and merge dependabot PR

- .github/dependabot.yml
- doc/changelog.d/677.fixed.md
Modify assignee for dependabot PR for auto approval
> Fix: Assign ci bot for dependabot PR

- .github/workflows/ci_cd.yml
- doc/changelog.d/678.dependencies.md
- pyproject.toml
Use python 3.9 - 3.12 for embedding tests
> Fix: Add matrix python in embedding test

- .github/workflows/ci_cd.yml
- doc/changelog.d/682.fixed.md
- tests/test_mechanical.py
- Add test report
- Remove pythonnet warning test
> Fix: Remove warning message test for remote session launch

- .github/workflows/ci_cd.yml
- doc/changelog.d/693.added.md
Adding Linkchecks after doc build
> Feat: Add link check

- .github/workflows/ci_cd.yml
- codecov.yml
- doc/changelog.d/692.changed.md
> Maint: Add code cov report

- doc/changelog.d/727.fixed.md
- src/ansys/mechanical/core/embedding/poster.py
- tests/embedding/test_app.py
> Fix: add return for poster

- doc/changelog.d/744.fixed.md
- tests/scripts/embedding_log_test.py
Add test cases for all log level.
> feat: Add more coverage on logging

- doc/changelog.d/753.added.md
- src/ansys/mechanical/core/run.py
- tests/test_cli.py
As the title says. Closes #659
> feat: raise an exception if port or input script aren't provided in batch mode

- .pre-commit-config.yaml
- doc/changelog.d/763.fixed.md
> FIX: Modify pre-commit hook

- .gitignore
- doc/changelog.d/776.fixed.md
- doc/source/_templates/autoapi/index.rst
- doc/source/api/path.rst
- src/ansys/mechanical/core/embedding/initializer.py
- tests/embedding/test_remote_solve.py
Removes disabling sec since it changes mechanical settings which causes issue with Background solve when using standalone Mechanical. This partially solves issue #719. This change will fix issue in Windows but not in Linux.
Test added only for windows
> Fix: Remove disable sec check 

- doc/changelog.d/796.miscellaneous.md
- doc/source/architecture.rst
Update architecture.rst based on suggestions
> docs: update architecture.rst

- doc/changelog.d/800.fixed.md
- doc/source/architecture.rst
Change "you implemented" to "is implemented"
> Fix sentence in architecture file

- .github/workflows/ci_cd.yml
- doc/changelog.d/803.changed.md
- Fixes nightly scheduled run failure.
- Update nightly run for 251_candidate
> MAINT: Update nightly runs for 251

- .github/workflows/ci_cd.yml
- doc/changelog.d/806.changed.md
keep all licenses related in global env
> MAINT: Refactor CICD

- doc/changelog.d/812.miscellaneous.md
- src/ansys/mechanical/core/embedding/viz/pyvista_plotter.py
- src/ansys/mechanical/core/embedding/viz/usd_converter.py
> fix exception when plotting a model with any line bodies

- doc/changelog.d/814.dependencies.md
- pyproject.toml
- Keep similar bounds for pyvista
> MAINT: Update dev version of pymechanical

- doc/changelog.d/815.changed.md
- doc/source/links.rst
Change ACT API Reference Guide link to the documentation on the dev portal
> Update ACT API Reference Guide link

- doc/changelog.d/821.dependencies.md
- doc/source/kil/index.rst
- pyproject.toml
> MAINT: Update pymech-env

- .gitignore
- doc/changelog.d/831.miscellaneous.md
- doc/source/user_guide_session/index.rst
> DOC: Add documentation for ``launch_mechanical``

- .github/labels.yml
- doc/changelog.d/836.changed.md
update platform specific labels
- Linux, windows, docker
> Maint: Update new labels

- doc/changelog.d/854.fixed.md
- src/ansys/mechanical/core/embedding/app.py
> use "OnWorkbenchReady" to update globals

- doc/changelog.d/857.fixed.md
- src/ansys/mechanical/core/embedding/viz/usd_converter.py
also remove the top level clr import to allow import at the global level
> Feat: add a layer to load into an existing stage

- doc/changelog.d/863.documentation.md
- doc/source/conf.py
- pyproject.toml
This PR temporarily disable cheatsheet. It will be integrated in another PR.
> MAINT: update ansys-sphinx-theme

- doc/changelog.d/871.documentation.md
- doc/source/cheatsheet/cheat_sheet.qmd
- doc/source/conf.py
- Update cheat sheet version automatically
- update comments that are going out of bounds
> MAINT: Cheat sheet

- doc/changelog.d/920.fixed.md
- src/ansys/mechanical/core/embedding/addins.py
- src/ansys/mechanical/core/embedding/initializer.py
- tests/embedding/test_dyna.py
It should be used on linux in the future, too.
> FIX: Use "lite" CLR host on windows for 251+

- .github/workflows/ci_cd.yml
- .github/workflows/label.yml
- .github/workflows/package_cleanup.yml
- doc/changelog.d/927.documentation.md
- doc/changelog.d/927.maintenance.md
- doc/source/cheatsheet/cheat_sheet.qmd
- doc/source/conf.py
- pyproject.toml
- Remove meilisearch
- Update ansys action to v8
> CHORE: Use static search

- .pre-commit-config.yaml
- doc/changelog.d/936.added.md
> FEAT: Automatically update pre-commit ci PR with prefix

- doc/changelog.d/937.maintenance.md
- src/ansys/mechanical/core/embedding/initializer.py
- src/ansys/mechanical/core/embedding/viz/utils.py
- src/ansys/mechanical/core/mechanical.py
- src/ansys/mechanical/core/pool.py
- src/ansys/mechanical/core/run.py
catch some of the exceptions, use error handling instead of assert.
> chore: Code maintenance 

- doc/changelog.d/947.maintenance.md
- pyproject.toml
- src/ansys/mechanical/core/embedding/background.py
- src/ansys/mechanical/core/examples/downloads.py
- src/ansys/mechanical/core/pool.py
- tests/embedding/test_background.py
- Use runtime error instead of assert
- Update downloading process
> chore: code maintenance

- .github/workflows/ci_cd.yml
- doc/changelog.d/971.maintenance.md
> CI: Update docs build action container

- .github/workflows/ci_cd.yml
- doc/changelog.d/965.maintenance.md
- tests/conftest.py
- tests/embedding/test_background.py
- tests/embedding/test_logger.py
> FIX: Update embedding script tests 

- doc/changelog.d/1000.documentation.md
- doc/source/getting_started/running_mechanical.rst
Minor update in docs related to #980
> DOCS: Update docs with new api

- doc/changelog.d/1037.added.md
- src/ansys/mechanical/core/embedding/enum_importer.py
- src/ansys/mechanical/core/embedding/imports.py
> FEAT: Update enum and globals

- doc/changelog.d/1065.test.md
- pyproject.toml
- tests/embedding/test_app.py
It didn't fully test what it was meant to
> test: update poster test

- doc/changelog.d/1072.fixed.md
- tests/embedding/test_app.py
Disabling till #1071 gets fixed
> FIX: Disable app poster test

- doc/changelog.d/1082.maintenance.md
- pyproject.toml
New version of ansys-sphinx-theme fixes doc build issues
> CHORE: Upgrade `ansys-sphinx-theme`

- doc/changelog.d/1083.maintenance.md
- pyproject.toml
> CHORE: update clr loader version

- .github/workflows/ci_cd.yml
- doc/changelog.d/1085.maintenance.md
`uv` helps reducing package installation time
> CHORE: Integrate uv in CI/CD

- doc/changelog.d/1099.documentation.md
- doc/source/getting_started/index.rst
This section is more about running containers than creating image as we already provide the image.
> DOCS: Update documentation for Mechanical container.

- .github/workflows/ci_cd.yml
- doc/changelog.d/1105.maintenance.md
> CI: Upload coverage to codacy

- .github/workflows/ci_cd.yml
- doc/changelog.d/1106.maintenance.md
- doc/changelog.d/changelog_template.jinja
- examples/embedding_n_remote/embedding_remote.py
This also fixes the example which is broken
> CHORE: Add solution status assert in example

- doc/changelog.d/1178.maintenance.md
- src/ansys/mechanical/core/examples/downloads.py
Example-data repo changed from master to main. Hence the changes.
> chore: Update the branch name to main

- doc/changelog.d/1197.documentation.md
- doc/source/getting_started/running_mechanical.rst
- doc/source/user_guide_session/server-launcher.rst
- src/ansys/mechanical/core/mechanical.py
Update `launch_mechanical` with correct usage.
> DOCS: Update `launch_mechanical` api usage examples

- SECURITY.md
- doc/changelog.d/1219.maintenance.md
> chore: Add security file

- doc/changelog.d/1223.fixed.md
- doc/source/conf.py
> fix(doc): remove duplication of metatag

- .github/labels.yml
- doc/changelog.d/1246.added.md
> feat: Add stale issue label

- .github/workflows/ci_cd.yml
- doc/changelog.d/1267.fixed.md
> FIX: Update latest release action

- doc/changelog.d/1282.documentation.md
- doc/source/user_guide_embedding/pep8.rst
- src/ansys/mechanical/core/embedding/license_manager.py
Update doc string for `disable_session_license` so that its less confusing
.
> DOCS: Update docstring

- doc/changelog.d/1299.documentation.md
- doc/source/examples/advanced_examples/index.rst
- doc/source/kil/index.rst
- doc/source/kil/pymechanical.rst
- doc/source/user_guide/howto/autocomplete.rst
- doc/styles/config/vocabularies/ANSYS/accept.txt
Address vale warnings in the documentation. This should fix the error in the ansys/actions workflow
> DOCS: Address vale warnings

- doc/changelog.d/1306.documentation.md
- doc/changelog.d/whatsnew.yml
> DOCS: Add pep8 in whatsnew

- doc/changelog.d/1320.maintenance.md
- doc/source/kil/index.rst
- doc/source/kil/mechanical.rst
- mechanical-env
- Update qt version in mechanical-env
- Remove support for old Mechanical version
> CHORE: Update qt version

- .github/workflows/setup-python/action.yml
- doc/changelog.d/1321.maintenance.md
> CHORE: Combine Python cache step into one and confirm Python is installed

- doc/changelog.d/1324.fixed.md
- pyproject.toml
> FIX: Add `mechanical-env` in wheel

- .github/workflows/ci_cd.yml
- doc/changelog.d/1334.added.md
Create post on Teams channel when the scheduled run fails
> feat: Notify maintainers when scheduled run fails
