- .github/workflows/ci_cd.yml
- README.rst
- doc/source/conf.py
- doc/source/contributing.rst
- doc/styles/Vocab/ANSYS/accept.txt
- pyproject.toml
The readme contains a lot of development information. IMO, this is too complex for the average user and it also duplicates much of our web documentation.
Let's simplify this by moving this development information out and into our contributing documentation.
Also updates our runners to use `public-ubuntu-latest-8-cores`.
> Simplify readme

- doc/source/conf.py
Changed url to get around Python 3.12's way of defining booleans
> changed python doc url to fix doc pipeline error

- docker/232/.dockerignore
.dockerignore  has a few more dependencies to support topo and smart tests.
> include dependencies to support topo and smart tests

- src/ansys/mechanical/core/__init__.py
- src/ansys/mechanical/core/mechanical.py
Exact same changes as in https://github.com/ansys/pymapdl/pull/2064
Original issue tracker https://github.com/ansys/pyfluent/issues/1588
Changes Windows data path to `%LocalAppData%\Ansys\ansys_mechanical_core`, same naming scheme as in https://github.com/ansys/pyfluent/pull/1615, https://github.com/ansys/pymapdl/pull/2064, https://github.com/ansys/pyprimemesh/pull/485, https://github.com/ansys/ansys-tools-path/pull/44, https://github.com/ansys/pysystem-coupling/pull/158
Changed `SETTINGS_DIR` to point to `USER_DATA_PATH` to make sure these two are always the same and avoid unnecessary `appdirs` use
Removed try-except block
Behavior not changed in this PR: data path/settings dir and examples folders are immediately created on `import ansys.mechnical.core`, might be worth changing to …
> Standardizing data paths

- .gitignore
- pyproject.toml
- tests/.gitignore
- tests/conftest.py
- tests/embedding/test_app.py
- tests/test_mechanical.py
I couldn't run the embedding unit tests locally anymore, and this change set fixes that. Fixes #247 
I also added some files to .gitignore that are artifacts of running remote session unit tests
> fix windows pythonnet warning unit tests

- CHANGELOG.md
- tests/conftest.py
- tests/embedding/test_logger.py
- tests/scripts/embedding_log_test.py
By default, pytest will run embedding tests using 2023R2
This allows a new command line argument to specify the version
pytest --ansys-version 241
to request a specific version.
In the future, we can mark specific tests as disabled for specific versions, once we add features that only work in newer versions. That's not done in this branch
> Add version configuration for embedding tests

- CHANGELOG.md
- pyproject.toml
This resolves the issue - TypeError: is_valid_executable_path() missing 1 required positional argument: 'exe_loc'
> Use updated ansys-tools-path.

- CHANGELOG.md
- src/ansys/mechanical/core/embedding/app.py
- src/ansys/mechanical/core/embedding/initializer.py
- tests/embedding/test_app.py
- tests/scripts/run_embedded_app.py
Created temporary user directories to allow for multiple instances of embedding to run in parallel. By default, private_appdata is False, meaning it will not create temporary user profiles when running an embedded instance. Since the temporary user directories are not fully removed at exit due to lingering licensing processes, I thought it would make sense to default private_appdata to False unless people want to run parallelly. I will be creating another issue to address fully removing the temporary directories. 
This PR relates to #279.
> Added private AppData functionality to embedding

- src/ansys/mechanical/core/embedding/initializer.py
Created more detailed pythonnet warning message with steps to uninstall pythonnet and reinstall ansys-pythonnet. This PR closes issue #281.
> Updated pythonnet warning message

- CHANGELOG.md
- pyproject.toml
- src/ansys/mechanical/core/embedding/loader.py
These are not needed now that we don't support python 3.7 anymore.
Fixes #288
> remove pkg-resources and importlib_metadata

- CHANGELOG.md
- src/ansys/mechanical/core/run.py
UnboundLocalError for version variable in run.py when running "ansys-mechanical -r {revn} -g" in the command line.
Closes #301
> Fix version issue running "ansys-mechanical -r {revn} -g"

- CHANGELOG.md
- src/ansys/mechanical/core/run.py
Added user warning when ansys-mechanical is run with the -i option (input script).
> Added warning for ansys-mechanical when provided an input script

- CHANGELOG.md
- src/ansys/mechanical/core/run.py
Removed duplicate warning message and adjusted the warning so that it only runs in batch mode with an input script when the revision is under 241.
> Fixed warning message for ansys-mechanical

- .github/workflows/ci_cd.yml
- CHANGELOG.md
- pyproject.toml
- src/ansys/mechanical/core/embedding/initializer.py
- src/ansys/mechanical/core/embedding/loader.py
- tests/embedding/test_app.py
- tests/embedding/test_logger.py
- tests/scripts/run_embedded_app.py
Use an easier to find path name
don't give a stack trace for warning
don't use virtual environments for tests
pass version number into tests
don't use exceptions for flow control in test file
> Minor private appdata updates

- CHANGELOG.md
- pyproject.toml
- src/ansys/mechanical/core/embedding/app.py
- src/ansys/mechanical/core/embedding/loader.py
- src/ansys/mechanical/core/embedding/runtime.py
don't support pythonnet 2.x
pin clr-loader for dependencies, not for tests
> update clr-loader dependency

- .github/workflows/ci_cd.yml
- CHANGELOG.md
Added "max-parallel: 2" for embedding test runs, since the license server should be able to handle two concurrent runs. This could resolve manually cancelling and re-running embedding tests that are running longer than expected.
> Max parallel 2 for embedding tests - ci_cd.yml

- CHANGELOG.md
- doc/source/conf.py
As title says - PyPIM moved to the multiversioning scheme causing some of these links to break
> fix: issues with PyPIM object.inv

- CHANGELOG.md
- README.rst
- doc/source/index.rst
Per Landon’s request in the PyAnsys Global AFT on 7/26/23, add a link to the PyMechanical cheat sheet from this library's documentation.
Note: This library doesn't reuse the README content in the overall index.rst file for documentation. Consequently, I had to add a new "Documentation and issues" section in both the README and the overall index.rst file.
@RobPasMue Landon also requested that a link to a cheat sheet be added beneath the documentation link on the repository page. However, I don't know if this can be done--and don't have the permissions to make changes to this page. If it's possible, someone with the permissions should consider adding a link--probably to the PNG file? Also, there are six more libraries that have cheat sheets. Before adding this same content to the others, I …
> Add links for doc and cheat sheet

- .github/workflows/ci_cd.yml
- CHANGELOG.md
Added scheduled cron to run the tests in ci_cd.yaml using 241 only. 
- Note: the scheduled cron only runs on the main branch. Depending on how busy the github runners are, there may be a 5-15 minute delay in the workflow actually running. If it's delayed for too long, it will skip the run altogether. We may need to troubleshoot a different time if it ends up skipping the scheduled run each day. 
- The cron is in UTC time, so it runs at 5pm CT, 6pm EST, and midnight CEST.
Added inputs to the workflow_dispatch to give flexibility in testing code for different revisions. Currently, the default revision is 231, and the test revision is 232. The test revision is 232 because it was listed in the "experimental" section of the tests, where tests under that revision are allowed to fail. 
This …
> Set up daily run for 241 testing and added manual inputs for workflow dispatch

- CHANGELOG.md
- src/ansys/mechanical/core/embedding/app.py
> use Application.Exit() in 241+

- .github/workflows/ci_cd.yml
- CHANGELOG.md
- tests/embedding/test_qk_eng_wb2.py
- .workbench_lite
- DSTreeScript.js
https://github.com/ansys/pymechanical/pkgs/container/mechanical
https://github.com/ansys/pymechanical/actions/runs/6217148574
https://github.com/ansys/pymechanical/actions/runs/6217493970/job/16872662814#step:11:1
> Adding Test case for export off screen image from Mechanical

- CHANGELOG.md
- tests/embedding/test_logger.py
before running embedding_log_test.py
that script sets logging environments and these could conflict with it
The env vars set in the docker container were affecting test runs against 241
> unset all logging environment variables

- CHANGELOG.md
- tests/conftest.py
Make pytest fixture, --ansys-version, dependent on the existing install. If it can't find one, then it defaults to 232
Closes #435
> pytest --ansys-version dependent on existing install

- CHANGELOG.md
- src/ansys/mechanical/core/embedding/app.py
app.save() should be able to save already saved project as well. if we send None in DataModel.Project.Save(None) mechanical API then it throws error "Null or Empty File Path."
This is fix for issue: https://github.com/ansys/pymechanical/issues/451
> Adds a check if path is None in app.save method

- CHANGELOG.md
- examples/embedding_n_remote/embedding_remote.py
Use ansys tool path to determine the version of the mechanical install on the system. If it can't find an install, the version defaults to 232
> Flexible version for embedding & remote example

- .github/workflows/ci_cd.yml
- CHANGELOG.md
Changed variable names in the revn-variations section and added more comments to clarify code
> Updated wording for revn-variations section

- CHANGELOG.md
- tests/embedding/test_app.py
use NamedTemporaryFile to create a temporary file instead of mktemp
> Update temporary file creation in test_app

- CHANGELOG.md
- src/ansys/mechanical/core/embedding/appdata.py
- Added env["TMP"] and env["TEMP"] paths for private_appdata to fix the issue when AnsysWBU.exe encounters a problem and the diagnostic file is written to C:\Users\username\AppData\Local\Temp\number\AnsysWBDumpFile.dmp
- Added a "PyMechanical-AppData" folder that contains "PyMechanical-pid" folders to make deleting the temporary appdata directories manually easier. This could be removed once the complete deletion of the PyMechanical-pid folders works
> Fix private appdata environment variables and folder layout

- .github/workflows/ci_cd.yml
- CHANGELOG.md
- tests/embedding/test_app.py
- tests/test_mechanical.py
Change Popen.wait() to Popen.communicate() due to this warning: https://docs.python.org/2/library/subprocess.html#subprocess.Popen.wait
Removed max_parallel in embedding test section
Closes #460
> Fix hanging embedding tests

- .github/workflows/ci_cd.yml
- CHANGELOG.md
Runs 241 and 242 nightly, with 241 being stable and 242 being experimental.
Still working on improving the workflow in fix/workflow-versions, but this change should be fine in the meantime for incorporating 242 testing.
> Add 242 to scheduled nightly run

- .github/workflows/ci_cd.yml
- CHANGELOG.md
Fixes the issues in https://github.com/ansys/pymechanical/actions/runs/7300442441/job/19895293745. Dependabot is properly configured but updates on a weekly basis, so this update was no triggered yet.
> ci: update ansys/actions to v5

- .github/workflows/ci_cd.yml
- CHANGELOG.md
- Updated stable version to be 241 and test version to be 242
- Changed variable names in revn-variations (used "test" instead of experimental)
- Changed environment variable names (removed "experimental" env variable, only have "stable" or "dev")
- Added a config-matrix section to configure the matrix for tests depending on whether or not it's a scheduled run. If it's a scheduled run, it runs all of the mechanical versions in the tests. Otherwise, it only runs the tests with the test docker image version
The embedding test workflow instability will be addressed in a separate PR
> Update workflow versions to run 241 and 242

- .github/workflows/ci_cd.yml
- CHANGELOG.md
Changing nightly run image version to take new candidate image (242)
> Maint: Update nightly run image version

- CHANGELOG.md
- src/ansys/mechanical/core/embedding/app.py
- src/ansys/mechanical/core/embedding/poster.py
- src/ansys/mechanical/core/embedding/runtime.py
- tests/embedding/test_app.py
`Poster` allows background threads to post to the main thread of mechanical.  This is necessary because mechanical is not
thread safe (or even thread compatible). Mechanical's API doesn't work on background threads.
> add poster

- CHANGELOG.md
- src/ansys/mechanical/core/embedding/initializer.py
> Feat: Block 32 bit python for embedding

- CHANGELOG.md
- doc/source/conf.py
removes Setting num of cores in conf.py. This way pdf build not creating an embedded app and hence not giving error.
> Test : pdf action 

- doc/changelog.d/688.fixed.md
- tests/conftest.py
- tests/test_mechanical.py
Use `get_mechanical_path` instead of `find_mechanical` in `remote_session_launch` tests
> Fix: Modify retrieving path of Mechanical in tests

- doc/changelog.d/701.dependencies.md
- pyproject.toml
- src/ansys/mechanical/core/embedding/viz/usd_converter.py
The API isn't so clean yet. An example script looks like this:
```
import ansys.mechanical.core as mech
project_file=r"D:\path\to\project.mechdat"
usda_file = r"D:\path\to\scene.usda"
app = mech.App(version=242, db_file=project_file)
app.open(project_file)
print(app)
from ansys.mechanical.core.embedding.viz.usd_converter import to_usd_file
print(f"converting {project_file} to usda at {usda_file}")
to_usd_file(app, usda_file)
```
> add open-usd exporter

- .github/workflows/ci_cd.yml
- doc/changelog.d/720.fixed.md
Extra newline in the upload coverage-file-tests step caused "coverage-file-tests" to not be uploaded, which made merging coverage fail
> fix: merging coverage step in ci_cd

- .github/workflows/ci_cd.yml
- doc/changelog.d/721.fixed.md
Currently coverage for remote connects are being published only for stable image versions. This causes issue in nightly run where image is test version(242). Hence unable to do merge coverage.
> fix: Publish coverage for remote connect

- doc/changelog.d/739.added.md
- tests/embedding/test_app.py
add additional case for deprecation warning
> feat: Add test for deprecation warning

- doc/changelog.d/740.fixed.md
- doc/source/user_guide_embedding/libraries.rst
- src/ansys/mechanical/core/embedding/app_libraries.py
- tests/embedding/test_app.py
- tests/embedding/test_app_libraries.py
fix `add_mechanical_python_libraries` to take the app itself rather than the version number.
> fix: adding mechanical libraries

- .github/workflows/ci_cd.yml
- doc/changelog.d/746.fixed.md
solves issue on release workflow where we have multiple image
> fix: Display image and build info only for scheduled run

- .github/workflows/ci_cd.yml
- doc/changelog.d/748.fixed.md
Release workflow runs the remote tests on 3 images which uploads coverage files with same name and causes below issue
https://github.com/ansys/pymechanical/actions/runs/9209141487/job/25333060420
> fix: upload coverage files only for latest stable version on release workflow

- doc/changelog.d/750.changed.md
- docker/231/Dockerfile
- docker/232/Dockerfile
- docker/241/Dockerfile
Cleaning up the apt cache and removing /var/lib/apt/lists helps keep the image size down. Since the RUN statement starts with apt-get update, the package cache will always be refreshed prior to apt-get install.
Clean up must be performed in the same RUN step, otherwise it will affect image size.
> MAINT: Delete the apt-get lists after installing packages

- doc/changelog.d/758.added.md
- doc/source/api/embedding.rst
- doc/source/api/index.rst
Add Embedding API references in Documentation
> Doc: Add embedding api references

- src/ansys/mechanical/core/embedding/appdata.py
As mentioned in issue https://github.com/ansys/pymechanical/issues/738. Provided an option not to copy profiles by default it will as the code used to
> Feat: Add option not to copy app data all the time

- doc/changelog.d/772.fixed.md
- src/ansys/mechanical/core/embedding/app.py
- tests/conftest.py
This fixes the nightly runs issue. It's a weird failure mode...
I added the event handlers for updating the globals which doesn't work when running on pythonnet. Since this happens in the constructor, this will throw an exception and the atexit handler will be called, which also throws an exception. Apparently, this will cause the asyncio-based subprocess handling to hang. I'm not sure why this only seems to affect 242...
> fix pythonnet issue

- .pre-commit-config.yaml
- doc/changelog.d/782.changed.md
Added recursion back to the add-license-headers hook
> chore: bump add-license-headers version to 0.3.2

- doc/changelog.d/784.fixed.md
- src/ansys/mechanical/core/embedding/app.py
Tested with embedded examples - https://github.com/ansys/pymechanical-embedding-examples/pull/203
> fix sharing app instances, clarify contract

- doc/changelog.d/790.added.md
- doc/source/user_guide_embedding/globals.rst
- src/ansys/mechanical/core/embedding/app.py
- src/ansys/mechanical/core/embedding/imports.py
- tests/embedding/test_globals.py
- app.Graphics
- Globals such as Point, Point2D, Vector3D etcs
> FEAT: Add graphics and globals

- doc/changelog.d/804.added.md
- src/ansys/mechanical/core/embedding/app.py
- tests/embedding/test_app.py
> FEAT: Update print_tree method

- .github/workflows/ci_cd.yml
- doc/Makefile
- doc/make.bat
usage: ``.\doc\make.bat html-noplot``
This is helpful if you want to generate docs without having to run Mechanical for examples @ansys/pyansys-core
> Feat: Add option for generating docs without examples

- doc/changelog.d/829.added.md
- doc/source/kil/mechanical.rst
- Mechanical crash on shutdown in Linux
> DOC: Update known issues and limitations

- doc/changelog.d/846.added.md
- pyproject.toml
- src/ansys/mechanical/core/embedding/app.py
- src/ansys/mechanical/core/embedding/viz/embedding_plotter.py
- Integrate ansys-visualization tool
> Feat: Integrate ansys visualization tool

- doc/changelog.d/855.fixed.md
- pyproject.toml
Closes #778 - Had to remove the `underlines` section with blank strings in order for the characters to appear under the section title
> fix: underline issue with changelog.rst section generation

- doc/changelog.d/858.fixed.md
- src/ansys/mechanical/core/embedding/viz/embedding_plotter.py
- src/ansys/mechanical/core/embedding/viz/usd_converter.py
- src/ansys/mechanical/core/embedding/viz/utils.py
- test.py
Separate getting the mechanical scene from converting that scene to USD. Because mechanical isn't threadsafe, getting the scene must be done on mechanical's main thread, while converting to USD can be done on any thread.
> Refactor usd export

- doc/changelog.d/888.documentation.md
- doc/source/conf.py
fix section with only 5 items.
currently there are 7 items
> DOCS: Fix doc layout

- .github/workflows/ci_cd.yml
- doc/changelog.d/895.fixed.md
with new release https://github.com/actions/upload-artifact/releases/tag/v4.4.0
``include-hidden-files`` should be added for uploading hidden files. This is required for ``.cov `` files which are needed for testing coverage
> FIX: Adapting braking change for upload action

- doc/changelog.d/894.fixed.md
- src/ansys/mechanical/core/embedding/app.py
- tests/embedding/test_app.py
- Return value of executed script
- add tests
> FIX: Update ``execute_script`` method

- doc/changelog.d/902.added.md
- src/ansys/mechanical/core/embedding/app.py
- tests/embedding/test_app.py
Leverage `execute_script` method for executing scripts from file
> FEAT: Add method to execute script from file for embedding

- doc/changelog.d/911.fixed.md
- doc/source/links.rst
Fix the `ACT API Reference Guide` link and add the `Mechanical scripting interface` link for documentation references
> fix: documentation links

- src/ansys/mechanical/core/embedding/app.py
- src/ansys/mechanical/core/embedding/initializer.py
use the ``warnings`` module to issue a warning instead of raising it as an exception.
> fix: Warning for multiple version

- doc/changelog.d/957.added.md
- src/ansys/mechanical/core/embedding/app.py
As the title says. This will improve app interaction with autocomplete
> feat: add typehints to ExtAPI, Tree, and Graphics

- doc/changelog.d/951.added.md
- src/ansys/mechanical/core/embedding/app.py
- tests/embedding/test_app.py
deletes existing files so that new files can be saved in that location
Closes #900
> feat: Add overwrite option for `App.save_as()`

- doc/changelog.d/952.fixed.md
- pyproject.toml
- src/ansys/mechanical/core/ide_config.py
- tests/conftest.py
- tests/test_cli.py
Tests run fine on 242, but fails in candidate because cli_impl takes mechanical path from local installed path. hence `ansys-mechanical-ideconfig` will throw exception.
> fix: stubs CLI test

- doc/changelog.d/950.fixed.md
- src/ansys/mechanical/core/embedding/background.py
- src/ansys/mechanical/core/embedding/ui.py
- src/ansys/mechanical/core/launcher.py
- Change `pass` to `raise Exception`
- Add `# no sec` lines to subprocesses where the arguments are known/valid
- Remove `shell=True` from subprocess
> fix: bandit warnings

- doc/changelog.d/980.added.md
- doc/source/cheatsheet/cheat_sheet.qmd
- src/ansys/mechanical/core/__init__.py
- src/ansys/mechanical/core/mechanical.py
- tests/conftest.py
If an instance of Mechanical is already running in specific port, this allows to connect to that using `ansys.core.mechanical.Mechanical`
ex:
Connect to an existing Mechanical instance at IP address ``192.168.1.30`` on port
``50001``..
>>> from ansys.mechanical.core import connect_to_mechanical
>>> pymech = connect_to_mechanical(ip='192.168.1.30', port=50001)
> FEAT: Adding new method for connecting to Mechanical instance

- doc/changelog.d/986.added.md
- src/ansys/mechanical/core/embedding/app.py
- src/ansys/mechanical/core/embedding/appdata.py
- src/ansys/mechanical/core/run.py
- tests/embedding/test_app.py
- tests/embedding/test_appdata.py
- tests/scripts/run_embedded_app.py
- Update private app data creation to have copy_profile option
eg: ``App(private_appdata=True, copy_profile=False)``
- Move appdata tests to new file and add tests for UniqueUserProfile creation,
~45% increase in coverage
> FEAT: Update private app data creation and add tests

- .pre-commit-config.yaml
- doc/changelog.d/993.maintenance.md
- src/ansys/mechanical/core/embedding/app.py
- Update `save_as` function with respect different version
- Update doc strings for ``App``
> FEAT: Update docstring and ``App.save_as()``

- .github/workflows/ci_cd.yml
- tests/conftest.py
- tests/embedding/test_logger.py
There is no crash on shutdown for 251+, but there was still some tests that allowed subprocesses without exceptions to throw a nonzero result. I modified this to only be the case for <251.
Here's the pipeline run for 251: https://github.com/ansys/pymechanical/actions/runs/12652827509
> fix: Process return code

- doc/changelog.d/1022.added.md
- src/ansys/mechanical/core/embedding/app.py
- src/ansys/mechanical/core/embedding/ui.py
- tests/embedding/test_app.py
Add ``project_directory`` property to App.
> FEAT: Add project directory property

- doc/changelog.d/1038.added.md
- src/ansys/mechanical/core/embedding/poster.py
- tests/embedding/test_app.py
> feat: add poster method that raises an exception

- README.rst
- doc/changelog.d/1061.documentation.md
- doc/source/conf.py
- doc/source/kil/index.rst
- doc/source/user_guide_scripting/index.rst
- If someone is having issues with PyMechanical, they should create an issue or discussion in PyMechanical
- If someone has a question about Mechanical scripting, they should create a post on the developer portal
- Also added booleans to conf.py to turn on/off building the cheatsheet or examples. By default, it builds the cheatsheet & examples
Addresses #473
> docs: Clarify support guidelines

- doc/changelog.d/1088.fixed.md
- src/ansys/mechanical/core/embedding/rpc/client.py
- src/ansys/mechanical/core/embedding/rpc/server.py
- tests/conftest.py
> FIX: Embedding rpc server shutdown

- doc/changelog.d/1096.documentation.md
- doc/changelog.d/whatsnew.yml
> docs: Add "what's new" fragment for the globals parameter in App

- doc/changelog.d/1090.added.md
- doc/changelog.d/1090.fixed.md
- src/ansys/mechanical/core/embedding/rpc/client.py
- src/ansys/mechanical/core/embedding/rpc/server.py
- src/ansys/mechanical/core/embedding/rpc/utils.py
> FIX: Remove unnecessary prints from embedding rpc

- .github/workflows/ci_cd.yml
- doc/changelog.d/1104.maintenance.md
rpc tests are failing only with 3.13 and hence coverage is not reported
> CHORE: Change main python version in CI/CD

- doc/changelog.d/1096.documentation.md
- doc/changelog.d/whatsnew.yml
- src/ansys/mechanical/core/embedding/rpc/client.py
- src/ansys/mechanical/core/mechanical.py
`launch_mechanical` now provides two rpc options such as `grpc` ( `backend = 'mechanical'`) and `rpyc`( `backend = 'python'`) . By default, it is `grpc`
It can be used as given below.
```python
import ansys.mechanical.core as pymechanical
mechanical = pymechanical.launch_mechanical(backend="python")
print(mechanical)
```
with `rpyc` option mechanical exists when python code completes.
with cleanup_on_exit option disabled , user can still use another client to connect the mechanical which is alive.
```python
import ansys.mechanical.core as pymechanical
mechanical = pymechanical.launch_mechanical(backend="python", cleanup_on_exit=False)
```
> FEAT: Add rpyc option in `launch_mechanical`

- doc/changelog.d/1091.added.md
- src/ansys/mechanical/core/__init__.py
- src/ansys/mechanical/core/embedding/app.py
- src/ansys/mechanical/core/embedding/initializer.py
```
INFO -  -  app - log_info - Starting Mechanical Application
INFO -  -  initializer - _get_latest_default_version - Existing Mechanical versions found: [232, 241, 242, 251, 252, 252]
WARNING -  -  initializer - _get_latest_default_version - Multiple versions of Mechanical found! Using latest version 252 ...
```
> FEAT: add logging for app

- doc/changelog.d/1098.documentation.md
- doc/changelog.d/whatsnew.yml
- doc/source/cheatsheet/cheat_sheet.qmd
- doc/source/conf.py
- doc/source/user_guide_embedding/globals.rst
- doc/source/user_guide_embedding/index.rst
- doc/source/user_guide_session/index.rst
- Clarify when to use ``app.update_globals(globals())`` vs. ``app = App(globals=globals())`` (If you want to exclude enums in global vars, you should use ``app.update_globals(globals(), False)``
- Update cheatsheet with globals parameter
> docs: Adjust globals documentation

- doc/changelog.d/1153.fixed.md
- src/ansys/mechanical/core/embedding/initializer.py
The windows store python uses windows secure DLL loading (via the Win32 API `SetDefaultDllDirectories`), which is not enabled in the python.org distribution. PyMechanical internally changes the process `PATH` environment variable for DLL loading, which does not work if secure DLL loading is used.
A future version of Mechanical may support secure DLL loading, but for the current releases PyMechanical can work around the issue by calling `os.add_dll_directory()`
Fixes  #1136
> fix: add workaround for windows store

- doc/changelog.d/1156.test.md
- tests/embedding/test_analytics.py
- tests/embedding/test_logger.py
- tests/scripts/run_analytics.py
Now that 25.2 nightly builds have stabilized, I can add the test case
> test: add test case for analytics capture 

- .github/workflows/ci_cd.yml
- doc/changelog.d/1162.fixed.md
`ansys/actions/release-github@v9` fails without token
> fix: Add token for release to github ansys/actions v9

- doc/changelog.d/1171.fixed.md
- src/ansys/mechanical/core/embedding/app.py
- tests/embedding/test_globals.py
- tests/scripts/run_embedded_app.py
Add `self._messages = None` to the BUILDING_GALLERY section of the App initialization so the following AttributeError does not occur when running `make -C doc html`:
```
app.messages.show()
if self.messages is not None:
^^^
AttributeError: 'App' object has no attribute '_messages'. Did you mean: 'messages'?
```
> fix: Add `self._messages` to BUILDING_GALLERY section in app initialization

- .github/workflows/ci_cd.yml
- doc/changelog.d/1188.maintenance.md
Update to use 26R1 in scheduled ci/cd runs
> chore: Update docker image version for nightly run

- doc/changelog.d/1187.fixed.md
- src/ansys/mechanical/core/ide_config.py
@dipinknair encountered multiple `site-packages` locations in a virtual environment (`lib/site-packages/` and `lib64/site-packages`). The `ansys-mechanical-ideconfig` command was raising an exception when there were more than one `site-packages` locations, so this PR considers that possibility
> fix: Consider multiple `site-packages` folders

- .github/workflows/ci_cd.yml
- doc/changelog.d/1200.maintenance.md
We should be uploading the docs using the bot token if I am not mistaken. Otherwise, the commit gets assigned to whomever triggers the workflow.
> ci: upload docs using the bot's token

- doc/changelog.d/1208.fixed.md
- src/ansys/mechanical/core/embedding/initializer.py
- tests/embedding/test_app_libraries.py
261 to be removed if/when it becomes an opt-out there.
I tested 261 & 252 on linux using github actions - both pass.
I tested 261 & 252 on windows locally, 252 had an issue with and without my changes, 261 was all good
One of the 252 issues was due to an incorrect usage of ansys-tools-path, which I fixed
> fix: add more versions to lite host

- doc/changelog.d/1232.fixed.md
- doc/source/user_guide_scripting/helper_scripts.rst
Added an important section to the script helpers page to clarify that what the bullet point describes can be found in the code section content of the link
> fix: Add important section to script helpers page for clarification

- .github/workflows/ci_cd.yml
- doc/changelog.d/1237.maintenance.md
25R2 is the stable version used in CI/CD. This change removes support of running test in 23R2.
> CI: Update ci/cd to use 25R2

- .github/workflows/ci_cd.yml
- doc/changelog.d/1259.fixed.md
Bug was fixed in dev version.
261 run: https://github.com/ansys/pymechanical/actions/runs/16631663405
> fix: Remove workaround for Documents folder

- doc/changelog.d/1278.fixed.md
- src/ansys/mechanical/core/embedding/initializer.py
- Fixes #1277 
- Update condition for 25R2
> FIX: Update windows store python workaround

- .github/workflows/ci_cd.yml
- doc/changelog.d/1288.maintenance.md
This pull request increases the timeout limits for several CI/CD test jobs in the `.github/workflows/ci_cd.yml` file. The main goal is to allow more time for these jobs to complete, likely to address issues with tests timing out.
**CI/CD workflow timeout adjustments:**
* Increased the `timeout-minutes` for the `embedding-tests` job from 15 to 30 minutes.
* Increased the `timeout-minutes` for the `embedding-scripts-tests` job from 15 to 30 minutes.
* Increased the `timeout-minutes` for the `launch-tests` job from 15 to 30 minutes.
* (Commented out) Increased the `timeout-minutes` for the `embedding-rpc-tests` job from 10 to 30 minutes.
> CHORE: Increase timeout for tests
